### ISSUE TITLE
finfo --csv broken under python 3.6

### ISSUE THREAD

**Issue by AlmogCohen** [ibmresilient/resilient-python-api#3]
It works perfectly with the same config under python 2.7

```
2018-10-16 13:47:27,009 Unverified HTTPS requests (cafile=false).
Traceback (most recent call last):
  File "/Users/almogcohen/.virtualenvs/algosec-resilient-SRjZugNj/bin/finfo", line 11, in <module>
    sys.exit(main())
  File "/Users/almogcohen/.virtualenvs/algosec-resilient-SRjZugNj/lib/python3.6/site-packages/resilient/bin/finfo.py", line 221, in main
    list_fields_csv(client, opts.field_type)
  File "/Users/almogcohen/.virtualenvs/algosec-resilient-SRjZugNj/lib/python3.6/site-packages/resilient/bin/finfo.py", line 141, in list_fields_csv
    print(iostr.getvalue().decode("utf-8"))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by MarkScherfling** [comment]
Thank you. We'll schedule a fix.

**Comment by mscherfling** [comment]
this is now fixed and the update is on pypi.
